# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Sanity Checks Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '21.0.0'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Lint Codebase
        run: yarn lint

      - name: Test::unit
        run: yarn test

      - name: Build
        run: yarn build
